version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:16-alpine
    container_name: collectionserver-postgres
    environment:
      POSTGRES_USER: collectionserver
      POSTGRES_PASSWORD: collectionserver_dev
      POSTGRES_DB: collectionserver
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U collectionserver"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - collectionserver-network

  garnet:
    image: ghcr.io/microsoft/garnet:latest
    container_name: collectionserver-garnet
    ports:
      - "6379:6379"
    networks:
      - collectionserver-network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Containerfile
    container_name: collectionserver-api
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DOTNET_RUNNING_IN_CONTAINER=true
      - IN_CONTAINER=true
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=collectionserver;Username=collectionserver;Password=collectionserver_dev
      - ConnectionStrings__CacheConnection=garnet:6379
    ports:
      - "5283:8080"
    depends_on:
      postgres:
        condition: service_healthy
      garnet:
        condition: service_started
    networks:
      - collectionserver-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  collectionserver-network:
    driver: bridge
