// <auto-generated />
using System;
using CollectionServer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CollectionServer.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CollectionServer.Core.Entities.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("idx_barcode");

                    b.HasIndex("MediaType")
                        .HasDatabaseName("idx_media_type");

                    b.HasIndex("Title")
                        .HasDatabaseName("idx_title");

                    b.ToTable("MediaItems", (string)null);

                    b.HasDiscriminator<int>("MediaType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CollectionServer.Core.Entities.Book", b =>
                {
                    b.HasBaseType("CollectionServer.Core.Entities.MediaItem");

                    b.Property<string>("Authors")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Genre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Isbn13")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("CollectionServer.Core.Entities.Movie", b =>
                {
                    b.HasBaseType("CollectionServer.Core.Entities.MediaItem");

                    b.Property<string>("Cast")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Director")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Genre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Rating")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer");

                    b.ToTable("MediaItems", t =>
                        {
                            t.Property("Genre")
                                .HasColumnName("Movie_Genre");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("CollectionServer.Core.Entities.MusicAlbum", b =>
                {
                    b.HasBaseType("CollectionServer.Core.Entities.MediaItem");

                    b.Property<string>("Artist")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Genre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("MediaItems", t =>
                        {
                            t.Property("Genre")
                                .HasColumnName("MusicAlbum_Genre");

                            t.Property("ReleaseDate")
                                .HasColumnName("MusicAlbum_ReleaseDate");
                        });

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("CollectionServer.Core.Entities.MusicAlbum", b =>
                {
                    b.OwnsMany("CollectionServer.Core.Entities.Track", "Tracks", b1 =>
                        {
                            b1.Property<Guid>("MusicAlbumId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Artist");

                            b1.Property<int>("DurationSeconds");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.Property<int>("TrackNumber");

                            b1.HasKey("MusicAlbumId", "__synthesizedOrdinal");

                            b1.ToTable("MediaItems");

                            b1.ToJson("Tracks");

                            b1.WithOwner()
                                .HasForeignKey("MusicAlbumId");
                        });

                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
